/**
 * Source of truth for robots.txt directives across environments.
 * Edit here, then run `node scripts/sync-robots.mjs` to regenerate public/robots.txt.
 *
 * Three environments:
 *   - dev      → block everything (no indexing of preview)
 *   - staging  → block everything (lovable.app preview)
 *   - prod     → allow all known good bots, declare sitemap
 */

export const SITE_URL = {
  dev: "http://localhost:5173",
  staging: "https://ezbiz-fs-com.lovable.app",
  prod: "https://www.ezbiz-fs.com",
};

const ALLOWED_BOTS = [
  "Googlebot",
  "Bingbot",
  "Twitterbot",
  "facebookexternalhit",
  "Facebot",
];

/** @param {"dev"|"staging"|"prod"} env */
export function buildRobotsTxt(env) {
  const sitemap = `${SITE_URL[env]}/sitemap.xml`;

  if (env === "dev" || env === "staging") {
    return [
      `# Auto-generated by scripts/sync-robots.mjs (env: ${env})`,
      `# Non-production: block all crawlers`,
      ``,
      `User-agent: *`,
      `Disallow: /`,
      ``,
      `Sitemap: ${sitemap}`,
      ``,
    ].join("\n");
  }

  // prod: explicit allow per bot, then wildcard allow, then sitemap.
  const blocks = ALLOWED_BOTS.map(
    (bot) => `User-agent: ${bot}\nAllow: /\n`,
  ).join("\n");

  return [
    `# Auto-generated by scripts/sync-robots.mjs (env: ${env})`,
    `# Edit scripts/robots.config.mjs and re-run the sync script.`,
    ``,
    blocks.trim(),
    ``,
    `User-agent: *`,
    `Allow: /`,
    ``,
    `Sitemap: ${sitemap}`,
    ``,
  ].join("\n");
}
