// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fpclrbfqlyghdyitisox.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZwY2xyYmZxbHlnaGR5aXRpc294Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2NzEyNzAsImV4cCI6MjA3NDI0NzI3MH0.xhLxuKskoMuwdvB9-SNhui1EAAv0T5lmUe-LE6sMiWI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});